// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BufferWrapper`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `write`

String greet({required String name}) =>
    RustLib.instance.api.crateApiPhasetidaGreet(name: name);

double loadLevel({required String json}) =>
    RustLib.instance.api.crateApiPhasetidaLoadLevel(json: json);

U8Array16384 tickLines({
  required double timeInSecond,
  required double deltaTimeInSecond,
  required bool auto,
}) => RustLib.instance.api.crateApiPhasetidaTickLines(
  timeInSecond: timeInSecond,
  deltaTimeInSecond: deltaTimeInSecond,
  auto: auto,
);

void loadImageOffset({
  required double holdHeadHeight,
  required double holdHeadHighlightHeight,
  required double holdEndHeight,
  required double holdEndHighlightHeight,
}) => RustLib.instance.api.crateApiPhasetidaLoadImageOffset(
  holdHeadHeight: holdHeadHeight,
  holdHeadHighlightHeight: holdHeadHighlightHeight,
  holdEndHeight: holdEndHeight,
  holdEndHighlightHeight: holdEndHighlightHeight,
);

BigInt getBufferSize() => RustLib.instance.api.crateApiPhasetidaGetBufferSize();

void resetNoteState({required double beforeTimeInSecond}) => RustLib
    .instance
    .api
    .crateApiPhasetidaResetNoteState(beforeTimeInSecond: beforeTimeInSecond);

void clearStates() => RustLib.instance.api.crateApiPhasetidaClearStates();

class U8Array16384 extends NonGrowableListView<int> {
  static const arraySize = 16384;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array16384(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array16384.init() : this(Uint8List(arraySize));
}
